### ISSUE TITLE
Proyecto "Venta de Ropa Tradicional "

### ISSUE THREAD

**Issue by AmeliReyesHernandez** [SistemasTecTlaxiaco/actividad-10-proyecto-final-de-web-30-equipo-3#1]

**Comment by AmeliReyesHernandez** [comment]
[Proyecto Equipo 3.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-proyecto-final-de-web-30-equipo-3/files/10214431/Proyecto.Equipo.3.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
De acuerdo a la rúbrica han obtenido un 48% del 50% 
Esto debido a que su índice de figuras no mostraba el número de página correspondiente.

**Comment by AmeliReyesHernandez** [comment]
[Proyecto Equipo 3.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-proyecto-final-de-web-30-equipo-3/files/10214342/Proyecto.Equipo.3.pdf)

**Comment by josealfredo79** [comment]
corrigieron muy poco el proyecto

![image](https://user-images.githubusercontent.com/58342642/207431321-5873411e-6e43-46aa-9fb3-b7d3940b412f.png)

**Comment by josealfredo79** [comment]
Los objetivos especificos deben mejorar la redaccion

**Comment by josealfredo79** [comment]
Bien hecho
